[package]
name = "gitforce-runner"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
gitforce-common = { path = "../gitforce-common" }
gitforce-db = { path = "../gitforce-db" }
gitforce-sandbox = { path = "../gitforce-sandbox" }
gitforce-storage = { path = "../gitforce-storage" }
uuid = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
