[package]
name = "ci"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "ci"
path = "src/main.rs"

[dependencies]
gitforce-common = { path = "../../crates/gitforce-common" }
gitforce-db = { path = "../../crates/gitforce-db" }
gitforce-events = { path = "../../crates/gitforce-events" }
gitforce-ci = { path = "../../crates/gitforce-ci" }
gitforce-scheduler = { path = "../../crates/gitforce-scheduler" }
gitforce-process = { path = "../../crates/gitforce-process" }
futures = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
